/**
 * @file main.js
 * @description Demonstrates printing array items at timed intervals using both setInterval and setTimeout
 */

/**
 * Array of 30 items - mix of books, films, and foods (generated by ai)
 * @type {string[]}
 */
const itemsList = [
    // Books
    "To Kill a Mockingbird",
    "1984",
    "The Great Gatsby",
    "Harry Potter and the Sorcerer's Stone",
    "The Lord of the Rings",
    "The Alchemist",
    "Pride and Prejudice",
    "The Hunger Games",
    "The Hobbit",
    "Brave New World",
    
    // Films
    "The Shawshank Redemption",
    "The Godfather",
    "Pulp Fiction",
    "The Dark Knight",
    "Forrest Gump",
    "Inception",
    "The Matrix",
    "Interstellar",
    "Parasite",
    "Spirited Away",
    
    // Foods
    "Pizza Margherita",
    "Sushi",
    "Pad Thai",
    "Chocolate Cake",
    "Butter Chicken",
    "Tacos al Pastor",
    "Croissants",
    "Pho Soup",
    "Lasagna",
    "Cheesecake"
  ];
  
  /**
   * Prints array items with setInterval
   * Prints one item of the list every second until the list is completely printed
   */
  function printWithSetInterval() {
    console.log("==== Printing with setInterval ====");
    index = 0;

    //this function works without an explicit for loop because the function is called again every 1000 milliseconds so it repeat again and again until all the elements in the array are printed. It's like a "timed loop" where the same function are called again with a predefined interval that is static and the value of the index variable is updated every second and "stored" in the js memory. 
    const intervalId = setInterval(function() {
      console.log(index + 1 + ": " + itemsList[index]);
      index++;
      
      if (index >= itemsList.length) {
        clearInterval(intervalId);
        console.log("setInterval printing complete.");
        
        // Start the setTimeout version after completion
        printWithSetTimeout();
      }
    }, 1000);
  }
  
  /**
   * Prints array items with setTimeout using a for loop
   * Prints one item of the list every second using setTimeout, differently by set interval, execute the function when the time went out
   */
  function printWithSetTimeout() {
    console.log("\n==== Printing with setTimeout ====");
    
    for (let i = 0; i < itemsList.length; i++) {
      setTimeout(function() {
        console.log(i + 1 + ": " + itemsList[i]);
        
        // Print completion message after the last item
        if (i === itemsList.length - 1) {
          console.log("setTimeout printing complete.");
        }
      }, i * 1000);
    }
  }
  
  // Start the process
  printWithSetInterval();